<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Books
[
<!ELEMENT Books (Book+)>
<!ELEMENT Book (title?,isbn+, Zipcode|author, publish*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT Zipcode (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publish (#PCDATA)>
<!ATTLIST title name CDATA #IMPLIED>    
<!ATTLIST isbn no CDATA #IMPLIED>   
<!ATTLIST Zipcode zname CDATA #FIXED "232232323">
<!ATTLIST publish year CDATA #FIXED "1995"> 
]>
<Books>
    <Book>
        <title name="Sample Title">Introduction to XML</title>
        <isbn no="123456789">ISBN-123-456</isbn>
        <zipcode Zname="232232323">10001</zipcode>
        <publish year="1995">Samir Singh</publish>
    </Book>
</Books>